version: '3.3'

services:
  app:
    depends_on:
      - nginx
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "ruby app.rb"
    ports:
      - "8081:4567"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"

  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
