version: '3.3'

services:
  app:
    env_file: '.env'
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "bundle exec ruby app.rb"
    ports:
      - "4567:4567"