version: '3.3'

services:
  nginx:
    volumes:
      - "./services/nginx/tuykin.ru.conf:/etc/nginx/conf.d/tuykin.ru.conf"

  app:
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"