version: '3.3'

services:
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - "./services/nginx/tuykin.ru.conf:/etc/nginx/conf.d/tuykin.ru.conf"
    depends_on:
      - app

  app:
    env_file: '.env'
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "bundle exec ruby app.rb"
    ports:
      - "4567:4567"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"