default: &default
  adapter: postgresql
  encoding: UTF-8
  pool: 5
  username: 'dev'
  password: 'dev'
  timeout: 5000

stage:
  <<: *default
  database: workshop_stage

development:
  <<: *default
  database: workshop_development

test: &test
  <<: *default
  database: workshop_test